### PR TITLE
Redesigned website with Svelte

### PR DESCRIPTION
**Pull request by jeremyfell**

### CODE REVIEW

**Review by JanBobolz — APPROVED** [review]
Oh, wow. _Very_ nice! :) 

Thanks!

**Comment by JanBobolz** [comment]
For future work, I think I'd like the documentation (tab) to be more "on point". Maybe with a focus on non-obvious syntax features (since that's probably what people will look at it for).

Big fan of everything else! Love the environment tab and new tab options.

**Comment by JanBobolz** [comment]
(Feel free to merge if this is ready. The documentation can be tackled in another merge request later)

**Comment by jeremyfell** [comment]
> For future work, I think I'd like the documentation (tab) to be more "on point". Maybe with a focus on non-obvious syntax features (since that's probably what people will look at it for).

I'm planning to rewrite some of the documentation soon; from there we can decide what "subset" should be included on the website tab to make it more concise.

**Pull request merged**
